name: Build quilt
on:
   workflow_dispatch:
jobs:
    build1:
        name: Build quilt arm64
        runs-on: ubuntu-24.04-arm
        steps:
             - name: Setup Ubuntu
               run: |
                sudo apt update
                sudo apt install -y subversion build-essential gettext 2to3 python3-pyelftools python3-distutils-extra
             - name: checkout
               uses: actions/checkout@v4
             - name: compile quilt
               run: |
                git clone https://github.com/openwrt/openwrt.git
                cd openwrt
                echo "CONFIG_TARGET_bcm27xx=y" > .config
                echo "CONFIG_TARGET_bcm27xx_bcm2712=y" >> .config
                echo "CONFIG_ALL_KMODS=y" >> .config
                echo "CONFIG_EXPERIMENTAL=y" >> .config
                make defconfig
                make tools/quilt/compile -j$(nproc)
                rm -f .config
                rm -rf tmp
                rm -rf dl
                cd -
                tar -c openwrt | xz -T0 > openwrt.tar.xz

             - name: Delete tag
               uses: ClementTsang/delete-tag-and-release@v0.4.0
               with:
                delete_release: true
                tag_name: openwrt-arm64
               env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             - name: Create release
               uses: ncipollo/release-action@v1.14.0
               with:
                allowUpdates: true
                name: OpenWrt ARM64 ${{ env.D }}
                tag: openwrt-arm64
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt.tar.xz

    build2:
        name: Build quilt x64
        runs-on: ubuntu-24.04
        steps:
             - name: Setup Ubuntu
               run: |
                sudo apt update
                sudo apt install -y subversion build-essential gettext 2to3 python3-pyelftools python3-distutils-extra
             - name: checkout
               uses: actions/checkout@v4
             - name: compile quilt
               run: |
                git clone https://github.com/openwrt/openwrt.git
                cd openwrt
                echo "CONFIG_TARGET_bcm27xx=y" > .config
                echo "CONFIG_TARGET_bcm27xx_bcm2712=y" >> .config
                echo "CONFIG_ALL_KMODS=y" >> .config
                echo "CONFIG_EXPERIMENTAL=y" >> .config
                make defconfig
                make tools/quilt/compile -j$(nproc)
                rm -f .config
                rm -rf tmp
                rm -rf dl
                cd -
                tar -c openwrt | xz -T0 > openwrt.tar.xz

             - name: Delete tag
               uses: ClementTsang/delete-tag-and-release@v0.4.0
               with:
                delete_release: true
                tag_name: openwrt-x64
               env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             - name: Create release
               uses: ncipollo/release-action@v1.14.0
               with:
                allowUpdates: true
                name: OpenWrt x64 ${{ env.D }}
                tag: openwrt-x64
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt.tar.xz

